import math

# Pixel constants
WIDTH = 512
HEIGHT = 384
FPS = 30
SEGMENT_SIZE = 16

# Game modes
MENU_MODE = 0
GAME_MODE = 1
FRACTAL_MODE = 2
LOSE_MODE = 3

# Fractal constants
MAX_ITER = 40
BASE_C_REAL = -0.5
BASE_C_IMAG = 0.0
DIFFICULTY_BASELINE_C = complex(BASE_C_REAL, BASE_C_IMAG)
WINNING_TOLERANCE = 0.02
CHEWING_TIME_SECONDS = 15

# Julia set bounds
FRACTAL_MIN_X = -1.5
FRACTAL_MAX_X = 1.5
FRACTAL_MIN_Y = -1.5
FRACTAL_MAX_Y = 1.5

BUTTON_W = 160
BUTTON_H = 22
RAINBOW_COLORS = [8, 9, 4, 11, 5, 2, 13]
